### ISSUE TITLE
TypeError when running `--help`

### ISSUE THREAD

**Issue by pnadolny13** [gupy-io/tap-sensedata#6]
Hey! I'm getting this error when I ran `meltano invoke tap-sensedata --help` is there a way to not access config values for --help/--about?

```
Traceback (most recent call last):
  File "/Users/pnadolny/Documents/Git/GitHub/pnadolny/hub-utils/hub_utils/test_meltano_project/.meltano/extractors/tap-sensedata/venv/bin/tap-sensedata", line 5, in <module>
    from tap_sensedata.tap import Tapsensedata
  File "/Users/pnadolny/Documents/Git/GitHub/pnadolny/hub-utils/hub_utils/test_meltano_project/.meltano/extractors/tap-sensedata/venv/lib/python3.9/site-packages/tap_sensedata/tap.py", line 5, in <module>
    from tap_sensedata.streams import (
  File "/Users/pnadolny/Documents/Git/GitHub/pnadolny/hub-utils/hub_utils/test_meltano_project/.meltano/extractors/tap-sensedata/venv/lib/python3.9/site-packages/tap_sensedata/streams.py", line 18, in <module>
    class CustomDataStream(sensedataStream):
  File "/Users/pnadolny/Documents/Git/GitHub/pnadolny/hub-utils/hub_utils/test_meltano_project/.meltano/extractors/tap-sensedata/venv/lib/python3.9/site-packages/tap_sensedata/streams.py", line 22, in CustomDataStream
    ref_date_start = date.today() - timedelta(days=int(os.getenv("TAP_SENSEDATA_CUSTOM_DATA_REF_DATE_START")))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by Marcos314** [comment]
Hello @pnadolny13, I would like to inform you that the fix has been performed on [PR](https://github.com/gupy-io/tap-sensedata/pull/7). Thank you for informing us of the error, with the correction implemented I will be closing this issue.
